--- #YAML:1.0
name: NetworkInfo-Discovery-NetBIOS
version: 0.01
author: |-
  Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: |-
  NetworkInfo::Discovery extension to find NetBIOS services
license: perl
requires:
  Net::NBName: 0.25
  NetworkInfo::Discovery: 0.12
  Test::More: 0
provides:
  NetworkInfo::Discovery::NetBIOS:
    file: lib/NetworkInfo/Discovery/NetBIOS.pm
    version: 0.01
generated_by: Module::Build version 0.25
